Repository amida-tech/indaba-client, pull requests merged in 2019-02, with the labels that each got.

#540 Feature/inba 965 remove reset pw
  src/i18n/en.json
  src/reducers.js
  src/services/api/auth.js
  src/services/api/requests.js
  src/styles/profile/_profile-form.scss
  src/views/Profile/actionTypes.js
  src/views/Profile/actions.js
  src/views/Profile/components/ProfileForm.js
  src/views/Profile/components/ResetPasswordPanel.js
  src/views/Profile/components/index.js
  src/views/Profile/index.js
  src/views/Profile/reducer.js
Labels: enhancement

#541 [INBA-903] Changes that remove whitespace at the end of a survey and
  src/common/components/TitleChange/ProjectTitleModal.js
  src/common/components/TitleChange/SurveyTitleModal.js
  src/common/components/TitleChange/TitleForm.js
  src/common/reducers/projectReducer.js
  src/i18n/en.json
  src/styles/_styles.scss
  src/styles/createprojectwizard/_new-project-title-form.scss
  src/styles/createprojectwizard/_new-project-title.scss
  src/styles/modals/_title-form.scss
  src/views/CreateProjectWizard/components/NewProjectTitle.js
  src/views/CreateProjectWizard/components/NewProjectTitleForm.js
  src/views/CreateProjectWizard/components/index.js
  src/views/CreateProjectWizard/reducer.js
  src/views/ProjectManagement/actionTypes.js
  src/views/ProjectManagement/actions.js
  src/views/ProjectManagement/components/index.js
  src/views/ProjectManagement/reducer.js
Labels: bug, priority

#546 Feature/inba 940 check question completion
  src/common/components/Summary/index.js
  src/i18n/en.json
  src/views/Profile/actions.js
  src/views/Profile/components/ResetPasswordPanel.js
  src/views/Profile/reducer.js
  src/views/ProjectManagement/components/Modals/SurveyStatus/SurveyStatusForm.js
  src/views/SurveyBuilder/components/CreateSurveyPanel.js
Labels: enhancement

#548 Bug/inba 923 mp change stage permissions
  src/common/reducers/surveyReducer.js
  src/i18n/en.json
  src/styles/_fonts.scss
  src/styles/_styles.scss
  src/styles/common/_react-select-override.scss
  src/styles/main.scss
  src/styles/modals/stage/_stage-form.scss
  src/styles/modals/subject/_subject-form.scss
  src/views/ProjectManagement/components/Modals/Stage/StageForm.js
  src/views/ProjectManagement/components/Modals/Stage/index.js
  src/views/ProjectManagement/components/index.js
Labels: bug

#550 Bug/inba 975 weighted value row delete error
  src/styles/main.scss
  src/styles/surveybuilder/_dynamic-question.scss
  src/styles/surveybuilder/_weighted-value-input.scss
  src/views/SurveyBuilder/components/DynamicQuestion.js
  src/views/SurveyBuilder/components/WeightedValueInput.js
Labels: bug

#535 Feature/inba 961 + 986 remove grommet syling
  package.json
  src/common/components/EditableTextInput.js
  src/i18n/en.json
  src/styles/_account-tab.scss
  src/styles/_add-stages.scss
  src/styles/_editable-text-input.scss
  src/styles/_pm-all-users.scss
  src/styles/_pm-users-tab.scss
  src/styles/_preference-tab.scss
  src/styles/_stage-slot.scss
  src/styles/_status-card.scss
  src/styles/_styles.scss
  src/styles/_subject-list.scss
  src/styles/_tabs.scss
  src/styles/_validated-text-input.scss
  src/styles/common/_mixins.scss
  src/styles/common/_react-select-override.scss
  src/styles/common/_semantic_colors.scss
  src/styles/createprojectwizard/_new-project-title-form.scss
  src/styles/dashboard/_filter-input.scss
  src/styles/dashboard/_search.scss
  src/styles/main.scss
  src/styles/messages/_message.scss
  src/styles/modals/_add-user-form.scss
  src/styles/modals/_create-new-project.scss
  src/styles/modals/_modal.scss
  src/styles/modals/_task-options-form.scss
  src/styles/modals/_user-profile-form.scss
  src/styles/modals/stage/_stage-form.scss
  src/styles/modals/subject/_subject-form.scss
  src/styles/surveybuilder/_add-question-panel.scss
  src/styles/surveybuilder/_static-question.scss
  src/styles/taskreview/_flag-controls-form.scss
  src/styles/taskreview/_survey-presentation.scss
  src/styles/taskreview/_task-details.scss
  src/views/ProjectManagement/components/Workflow/StageSlot.js
  src/views/UserProfile/components/AccountTab.js
  yarn.lock
Labels: enhancement, priority

#558 Bug/INBA-976 Force task complete not updating state
  src/common/actionTypes/taskActionTypes.js
  src/common/actions/taskActions.js
  src/common/reducers/taskReducer.js
  src/services/api/tasks.js
  src/views/ProjectManagement/components/Modals/TaskOptions/index.js
Labels: b-b-backend, bug

#561 Bug/inba 976 force task not updating, forgot moveTask
  src/services/api/tasks.js
Labels: bug, priority

#557 Feature/inba 982 unassign task
  src/common/actionTypes/taskActionTypes.js
  src/common/actions/taskActions.js
  src/common/reducers/taskReducer.js
  src/i18n/en.json
  src/services/api/tasks.js
  src/views/ProjectManagement/components/Modals/TaskOptions/TaskOptionsForm.js
  src/views/ProjectManagement/components/Modals/TaskOptions/index.js
Labels: enhancement
